
-- Create the coffee_shops table to store scraped data
CREATE TABLE public.coffee_shops (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  rating real,
  review_count integer,
  category text,
  price text,
  description text,
  image text,
  city text NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT coffee_shops_name_city_key UNIQUE (name, city)
);

-- Enable Row Level Security on the table
ALTER TABLE public.coffee_shops ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows anyone to read the coffee shop data
CREATE POLICY "Allow public read access" ON public.coffee_shops
FOR SELECT USING (true);
