// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://joseqgmwmxvxpfoaiyna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impvc2VxZ213bXh2eHBmb2FpeW5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTUwNzUsImV4cCI6MjA2NTU3MTA3NX0.IBllAJHmPadVaP9X8jlEl7_ADY46djCmIVe_wHbHQEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);